version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/app
    steps:
      - checkout
      - run: ./.circleci/setup.sh
      - run: go get
      - run: make build
      - run: make test
