version: 2
jobs:
  build:
    docker:
      - image: nixos/nix
    steps:
      - checkout
      - run: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixos
      - run: nix-channel --update
      - run: nix-env -i gnumake
      - run: make ci
