version: 2
jobs:
  build:
    docker:
      - image: golang:1.13-alpine
    working_directory: ~/app
    steps:
      - checkout
      - run: ./.circleci/setup.sh
      - run: go get
      - run: make build
      - run: make test
      - run: make run
